[project]
name = "nb"
version = "0.1.0"
description = "notebook experimentation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.9",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "polars>=1.38.1",
]
